extends: .github

queue_rules:
  - name: default
    allow_inplace_checks: true
    conditions:
      - and: &CheckRuns
          - check-success=test
    speculative_checks: 5

  - name: lowprio
    allow_inplace_checks: true
    conditions:
      - and: *CheckRuns
    batch_size: 7
    batch_max_wait_time: 5min
    queue_branch_merge_method: fast-forward
    disallow_checks_interruption_from_queues:
      - default

pull_request_rules:
  - name: automatic merge
    conditions:
      - base=main
      - and: *CheckRuns
      - check-success=semantic-pull-request
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - label!=work-in-progress
      - label!=manual merge
    actions:
      queue:
        name: default

  - name: automatic merge from dependabot
    conditions:
      - and: *CheckRuns
      - author=dependabot[bot]
      - label!=work-in-progress
      - label!=manual merge
    actions:
      queue:
        name: lowprio
        method: merge

  - name: request review
    conditions:
      - -author=dependabot[bot]
      - -merged
      - -closed
      - and: *CheckRuns
      - "check-success=Rule: changelog requirements (post_check)"
      - "#approved-reviews-by=0"
      - "#changes-requested-reviews-by=0"
      - "review-requested!=@devs"
    actions:
      request_reviews:
        teams:
          - devs
