defaults:
  actions:
    queue:
      name: default
      method: rebase

queue_rules:
  - name: default
    conditions:
      - check-success=pep8
      - check-success=py310
    speculative_checks: 5

pull_request_rules:
  - name: automatic merge
    conditions:
      - base=main
      - check-success=pep8
      - check-success=py310
      - check-success=semantic-pull-request
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - label!=work-in-progress
      - label!=manual merge
    actions:
      queue:
        name: default
  - name: automatic merge from dependabot
    conditions:
      - author=dependabot[bot]
      - label!=work-in-progress
      - label!=manual merge
    actions:
      queue:
        name: default
        priority: low

  - name: dependabot conflict fixer
    conditions:
      - author=dependabot[bot]
      - conflict
    actions:
      comment:
        message: "@dependabot rebase"

  - name: dismiss reviews except for core devs
    conditions:
      - author!=@devs
    actions:
      dismiss_reviews: {}
  - name: dismiss reviews for core devs
    conditions:
      - author=@devs
    actions:
      dismiss_reviews:
        # Do not remove approval for core devs
        approved: False
  - name: auto add wip
    conditions:
      - title~=^(wip|WIP).*
    actions:
      label:
        add: ["work-in-progress"]
  - name: warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: "@{{author}} this pull request is now in conflict 😩"
      label:
        add:
          - conflict
  - name: remove conflict label if not needed
    conditions:
      - -conflict
    actions:
      label:
        remove:
          - conflict
  - name: warn on CI failure for hotfix
    conditions:
      - label=hotfix
      - "#check-failure>0"
    actions:
      comment:
        message: Your hotfix is failing CI @{{author}} 🥺
