[tool.poe.executor]
type = "poetry"

[tool.poe.tasks.test]
cmd = "pytest -v --pyargs mergify_cli"


[tool.poe.tasks.linters]
help = "Run linters"
default_item_type = "cmd"
sequence = [
  "ruff check .",
  "black --check .",
  "mypy",
]
